---
- hosts: localhost
  connection: local
  become: true

  tasks:
   
  - name: Install ansible community.general
    command: 'ansible-galaxy collection install community.general'
    changed_when: false

  - name: install packages
    package:
      name:
        - htop
        - tmux
        - tor
        - snapd
        - apache2
        - supervisor
        - unattended-upgrades 
        - apt-listchanges 
        - net-tools
      state: latest
      update_cache: yes
      
  - name: Install Certbot
    community.general.snap:
      name: 
        - core
        - certbot
      classic: yes

  - name: Setup Certbot
    command: 'ln -s /snap/bin/certbot /usr/bin/certbot'
    changed_when: false
     
  - name: Copy .bash_aliases
    copy:
      src: files/bash_aliases
      dest: /home/phil/.bash_aliases
      owner: phil
      group: phil
   
  - name: Copy .tmux.conf
    copy:
      src: files/tmux.conf
      dest: /home/phil/.bash_aliases
      owner: phil
      group: phil

  - name: add ansible user
    user:
      name: autome
      system: yes
 
  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_autome
      dest: /etc/sudoers.d/autome
      owner: root
      group: root
      mode: 0440
 
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: autome
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/NCLtech/ansible_conf_server.git
